package app.reverb.autolearn

import app.reverb.core.common.ReverbLog
import app.reverb.data.LearnedSiteConfig
import app.reverb.source.api.MediaDetails
import app.reverb.source.api.MediaItem
import app.reverb.source.api.VideoRef
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.jsoup.Jsoup
import org.jsoup.nodes.Element
import java.net.URI

/**
 * The LearnedSite interpreter — scrapes a site using a [LearnedSiteConfig] (CSS selectors
 * generated by the LLM analyzer or manually defined).
 *
 * Uses Jsoup to fetch + parse pages, then extracts structured data (catalog items, details,
 * episode lists) using the CSS selectors in the config. The native UI renders this data.
 *
 * Reference: PLAN.md §23.1 Layer 3.
 */
class LearnedSiteInterpreter(
    private val httpClient: OkHttpClient,
) {

    /** Fetch the catalog (homepage / popular grid) for a site. */
    suspend fun fetchCatalog(config: LearnedSiteConfig, page: Int = 1): List<MediaItem> = withContext(Dispatchers.IO) {
        val url = config.baseUrl
        ReverbLog.i("LearnedSite", "Fetching catalog from $url")
        val doc = fetchDocument(url) ?: return@withContext emptyList()

        val selector = config.catalogSelector
        if (selector.isNullOrBlank()) {
            ReverbLog.w("LearnedSite", "No catalogSelector in config — can't fetch catalog")
            return@withContext emptyList()
        }

        val cards = doc.select(selector)
        ReverbLog.d("LearnedSite", "Found ${cards.size} cards with selector '$selector'")

        val items = cards.mapNotNull { card -> parseCard(card, config, url) }
        ReverbLog.i("LearnedSite", "Catalog: ${items.size} items parsed")
        items
    }

    /** Fetch details for a specific media item. */
    suspend fun fetchDetails(config: LearnedSiteConfig, item: MediaItem): MediaDetails = withContext(Dispatchers.IO) {
        ReverbLog.i("LearnedSite", "Fetching details from ${item.url}")
        val doc = fetchDocument(item.url) ?: return@withContext MediaDetails(
            url = item.url, title = item.title, description = "Failed to load page"
        )

        val poster = config.detailsPosterSelector?.let { doc.selectFirst(it)?.absUrl("src") }
        val synopsis = config.detailsSynopsisSelector?.let { doc.selectFirst(it)?.text() }

        // Fetch episodes.
        val episodes = config.episodeListSelector?.let { epSelector ->
            if (epSelector.isNotBlank()) {
                doc.select(epSelector).mapNotNull { epEl ->
                    val href = epEl.absUrl("href").ifBlank { epEl.attr("href") }
                    val title = epEl.text().trim().ifBlank { "Episode" }
                    if (href.isNotBlank()) {
                        val fullUrl = resolveUrl(item.url, href)
                        VideoRef(url = fullUrl, title = title)
                    } else null
                }
            } else emptyList()
        } ?: emptyList()

        ReverbLog.i("LearnedSite", "Details: ${episodes.size} episodes found")
        MediaDetails(
            url = item.url,
            title = item.title,
            description = synopsis,
            posterUrl = poster ?: item.thumbnailUrl,
            thumbnailUrl = item.thumbnailUrl,
            episodes = episodes,
        )
    }

    private fun parseCard(card: Element, config: LearnedSiteConfig, baseUrl: String): MediaItem? {
        val title = config.cardTitleSelector?.let { card.selectFirst(it)?.text() }
        val thumbnail = config.cardThumbnailSelector?.let { card.selectFirst(it)?.absUrl("src") }
        val href = config.cardUrlSelector?.let { card.selectFirst(it)?.absUrl("href") }

        // If no specific selectors, try to infer from the card element.
        val resolvedTitle = title ?: card.text().trim().take(100)
        val resolvedHref = href ?: card.absUrl("href").ifBlank { card.selectFirst("a")?.absUrl("href") }

        if (resolvedHref.isNullOrBlank()) return null

        val fullUrl = resolveUrl(baseUrl, resolvedHref)
        return MediaItem(
            url = fullUrl,
            title = resolvedTitle.ifBlank { "Unknown" },
            thumbnailUrl = thumbnail ?: card.selectFirst("img")?.absUrl("src"),
        )
    }

    private fun fetchDocument(url: String): org.jsoup.nodes.Document? = try {
        val request = Request.Builder()
            .url(url)
            .header("User-Agent", app.reverb.core.network.UserAgentInterceptor.DEFAULT_UA)
            .build()
        httpClient.newCall(request).execute().use { resp ->
            val html = resp.body?.string() ?: return null
            Jsoup.parse(html, url)
        }
    } catch (e: Exception) {
        ReverbLog.e("LearnedSite", "Failed to fetch $url: ${e.message}", e)
        null
    }

    private fun resolveUrl(base: String, relative: String): String {
        if (relative.startsWith("http://") || relative.startsWith("https://")) return relative
        return try {
            URI(base).resolve(relative).toString()
        } catch (e: Exception) {
            relative
        }
    }
}
